name: 'ohlcv_dbt'
version: '1.0'
config-version: 2

profile: 'ohlcv_profile'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

models:
  ohlcv_dbt:
    +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: incremental
