FROM python:3.11-slim

WORKDIR /app

# Install netcat (for wait-for-kafka.sh)
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

COPY producer/producer.py .
COPY producer/wait-for-kafka.sh .

RUN chmod +x wait-for-kafka.sh

RUN pip install yfinance kafka-python

CMD ["sh", "wait-for-kafka.sh"]
